runtime: go116

# set to smallest vm size
instance_class: B1

basic_scaling:
  max_instances: 5

env_variables:
  GCLOUD_STORAGE_BUCKET: "data-dj-2021.appspot.com"

# redirect requests for static files from this url directly to the bucket
handlers:
- url: /archives
  static_dir: data-archive
