runtime: go117

# set to smallest vm size
instance_class: B1

basic_scaling:
  max_instances: 5

env_variables:
  DATA_BUCKET_NAME: "data-dj-2021.appspot.com"

# redirect requests for static files from this url directly to the bucket
handlers:
- url: /archives
  static_dir: data-archive
