services:
    
  redis:
    image: redis
    ports: 
        - "6379:6379"

  db:
    image: mongo
    ports: 
        - "27017:27017"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env.test
    ports: 
      - "8765:8765"
    volumes:
      - ./secrets:/app/secrets:ro
      - ./data:/data-mount

