# this docker-compose file is for testing purposes only!

services:
    
  redis:
    image: redis
    ports: 
        - "6379:6379"

  db:
    image: mongo
    ports: 
        - "27017:27017"
    volumes:
      - "./testsIntegration/mongoInit:/docker-entrypoint-initdb.d"
      - "./testsIntegration/testData:/testData"

  api:
    image: dataset-dj_api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env.test
    ports: 
      - "8765:8765"
    volumes:
      - ./secrets:/app/secrets:ro
      - ./data:/data-mount

  # image names have to be lower case
  taskhandler:
    image: dataset-dj_taskhandler:latest
    build:
      context: .
      dockerfile: Dockerfile.taskHandler
    env_file:
      - .env.test
    volumes:
      - ./secrets:/app/secrets:ro
      - ./data:/data-mount
