# this docker-compose file is for testing purposes only!
version: "3"
services:
    
  redis:
    image: redis
    restart: "no"
    ports: 
      - "6379:6379"

  db:
    image: mongo
    volumes:
      - "./testsIntegration/mongoInit:/docker-entrypoint-initdb.d"
      - "./testsIntegration/testData:/testData"
    ports: 
      - "27017:27017"
    restart: "no"

  api:
    image: registry.ethz.ch/bsunderland/data-dj-images/api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - ${ENV_FILE}
    ports: 
      - "8765:8765"
    volumes:
      - ./secrets:/app/secrets:ro
      - ./data:/data-mount
    depends_on:
      - db
      - redis
      - taskhandler
    restart: "no"

  taskhandler:
    image: registry.ethz.ch/bsunderland/data-dj-images/taskhandler:latest
    build:
      context: .
      dockerfile: Dockerfile.taskHandler
    env_file:
      - ${ENV_FILE}
    volumes:
      - ./secrets:/app/secrets:ro
      - ./data:/data-mount
    depends_on:
      - db
      - redis
    restart: "no"