apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: europe-west6-docker.pkg.dev/data-dj-2021/dj-docker-repo/dj-api@sha256:3cbf0fe1b44f97a25b742fde6eeaafb76f8f29e05105def88fccadf3b4a3114c
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: europe-west6
  name: dj-api
  namespace: '783088055312'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/vpc-access-connector: projects/data-dj-2021/locations/europe-west6/connectors/redis--connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
      name: dj-api-00002-gig
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: PROJECT_ID
          value: data-dj-2021
        - name: ARCHIVE_BASE_URL
          value: https://storage.googleapis.com/
        - name: SOURCE_BUCKET_NAME
          value: data-dj-2021.appspot.com
        - name: SOURCE_BUCKET_PREFIX
          value: data-mirror/
        - name: ARCHIVE_BUCKET_NAME
          value: data-dj-2021.appspot.com
        - name: ARCHIVE_BUCKET_PREFIX
          value: data-archive/
        - name: DB_CONNECTOR
          value: mongodb+srv://data-dj:LibLab123@archive-cluster.jzmhu.mongodb.net/data-dj-main?retryWrites=true&w=majorit
        - name: DB_NAME
          value: data-dj-main
        - name: GIN_MODE
          value: debug
        - name: EMAIL_ADDRESS
          value: datadj.service@gmail.com
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: ../gcloud-key-file.json
        - name: REDISHOST
          value: 10.27.193.115
        - name: REDISPORT
          value: '6379'
        - name: ADMIN_KEY
          valueFrom:
            secretKeyRef:
              key: '1'
              name: dj-admin-key
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: '1'
              name: dj-email-pw
        image: europe-west6-docker.pkg.dev/data-dj-2021/dj-docker-repo/dj-api@sha256:3cbf0fe1b44f97a25b742fde6eeaafb76f8f29e05105def88fccadf3b4a3114c
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
      serviceAccountName: data-dj-app@data-dj-2021.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
